vim.opt.autoindent = true           -- Good autoindent.
vim.opt.background = 'dark'         -- Tell vim what the background colors look like.
vim.opt.backup = false              --
vim.opt.belloff = "all"              -- No f-ing bell.
vim.opt.breakindent = true
vim.opt.clipboard = "unnamedplus"   -- Copy outside of vim.
vim.opt.cmdheight = 2               -- More space for displaying messages.
vim.opt.colorcolumn = "100"
vim.opt.cursorcolumn = true
vim.opt.cursorline = true            -- Enable highlightning of the current line.
vim.opt.expandtab = true            -- Convert tabs to spaces.
vim.opt.guicursor = "n-v-c:block,i:ver25-Cursor"  -- Change cursor when in insert mode
vim.opt.guifont = "Hack\\ Nerd\\ Font\\ Mono:h18"
vim.opt.hidden = true               -- Required to keep multiple buffers open.
vim.opt.hlsearch = false
vim.opt.ignorecase = true           -- Ignore case when searching.
vim.opt.incsearch = true            -- Make search act like in modern browsers.
vim.opt.isfname:append("@-@")
vim.opt.keywordprg = ":help"        -- Use K to access help for word under cursor
vim.opt.laststatus = 2              -- Always display statusline.
vim.opt.mouse = 'a'                 -- Enable mouse.
vim.opt.number = true               -- Line numbers
vim.opt.pumblend = 17
vim.opt.relativenumber = true
vim.opt.ruler = true                -- Always show cursor position
vim.opt.scrolloff = 8
vim.opt.scrolloff = 8               -- Keep a buffer to the top of the terminal.
vim.opt.shiftwidth = 4              -- Number of space characters inserted for indentation.
vim.opt.showbreak = string.rep(" ", 3)
vim.opt.showcmd = false
vim.opt.showmatch = true            -- Show matching brackets when text indicator is over them.
vim.opt.showmode = false 
vim.opt.sidescrolloff = 8           -- Keep a buffer to the side of the terminal.
vim.opt.signcolumn = 'yes:2'        -- Always show the signcolumn.
vim.opt.smartindent = true          -- Makes indenting somewhat smarter.
vim.opt.smarttab = true             -- Makes tabbing smarter.
vim.opt.softtabstop = 0             --
vim.opt.splitbelow = true           -- Always split horizontals to below
vim.opt.splitright = true           -- Always split verticals to the right
vim.opt.swapfile = false            -- No swapfile! :)
vim.opt.tabstop = 4                 -- Insert 2 spaces for a tab.
vim.opt.termguicolors = true
vim.opt.timeoutlen = 300            -- Default value is 1000ms!
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.updatetime = 50
vim.opt.wildignore = "__pycache__"
vim.opt.wildmode = "longest:full"
vim.opt.wildoptions = "pum"
vim.opt.wrap = false
vim.opt.writebackup = false         
